[build]
  publish = "."
  functions = "netlify/functions"
  edge_functions = "netlify/edge-functions"

[[redirects]]
  from = "/api/google-place"
  to = "/.netlify/functions/google-place"
  status = 200

[[redirects]]
  from = "/api/google-place-photo"
  to = "/.netlify/functions/google-place-photo"
  status = 200

[[redirects]]
  from = "/api/debug"
  to = "/.netlify/functions/debug"
  status = 200